### ISSUE TITLE
Tracking Issue Inline Mode

### ISSUE THREAD

**Issue by gugahoa** [telegram-rs/telegram-bot#121]
- [X] Initial Support (#119)
- [ ] rest of answerInlineQuery fields (https://core.telegram.org/bots/api#answerinlinequery)
- [ ] rest of InlineQueryResult variants (https://core.telegram.org/bots/api#inlinequeryresult)
- [ ] rest of InlineQueryResultArticle fields (https://core.telegram.org/bots/api#inlinequeryresultarticle)
- [ ] rest of InputMessageContent implementation (https://core.telegram.org/bots/api#inputmessagecontent)

**Comment by goweiwen** [comment]
I'll pick this up. Also looking into implementing [ChosenInlineResult](https://core.telegram.org/bots/api#choseninlineresult) in the near future.
