### ISSUE TITLE
Stickers tracking issue

### ISSUE THREAD

**Issue by knsd** [telegram-rs/telegram-bot#168]
- [ ]  Update Sticker struct and add MaskPosition struct
- [ ]  Add StickerSet struct
- [ ]  Add sendSticker request
- [ ]  Add getStickerSet request
- [ ]  Add uploadStickerFile request
- [ ]  Add createNewStickerSet request
- [ ]  Add addStickerToSet request
- [ ]  Add setStickerPositionInSet request
- [ ]  Add deleteStickerFromSet request

**Comment by dhalucario** [comment]
Heya, I implemented sendSticker in my repo, feel free to grab the implementation from it. https://github.com/dhalucario/telegram-bot/commit/ede3a675d28c43384a0a109d0e75edc361a4c494
